name: tests

on:
  push:
    branches: [master]
    paths:
      - ".github/workflows/*"
      - "src/**"
      - build.zig
  pull_request:
    branches: [master]
    paths:
      - ".github/workflows/*"
      - "src/**"
      - build.zig

jobs:
  unit-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.10.0
      - uses: extractions/setup-just@v1
      - name: clone packages
        run: just setup
      - name: Run unit tests
        run: just test
